basic_model:
  buildings: &basic_buildings
    - place: 1
    # prepare village
    - main: 10
      barracks: 10
      stable: 5
      smith: 10
      market: 10
      stone: 20
      iron: 20
      wall: 20
    # prepare snob
    - main: 20
      smith: 20
      snob: 1
    # converge village to best model to troops
    - barracks: 25
      stable: 15
      smith: 20
      statue: 1
      market: 20
      wood: 30
      stone: 30
      iron: 30
  train:
    spy: 1000

defense:
  train:
    spy: 2000
    sword: 0.5
    spear: 0.5
  buildings:
     - *basic_buildings
     - main: 30
       wood: 30
       stone: 30
       iron: 30

attack:
  train:
    spy: 2000
    axe: 0.5
    light: 0.5
    ram: 300
  buildings:
     - *basic_buildings
     - main: 30
       stable: 20
       garage: 10
       wood: 30
       stone: 30
       iron: 30

first_village:
  buildings:
  - wood: 2
    stone: 2
    iron: 1
  - main: 3
    barracks: 1
  - wood: 3
    stone: 3
    barracks: 2
  - storage: 2
  - iron: 2
    storage: 3
  - barracks: 3
  - statue: 1
  - farm: 2
    iron: 3
  - main: 5
    smith: 1
  - wood: 4
    stone: 4
  - storage: 2
  - iron: 2
    storage: 3
  - statue: 1
  - iron: 3
    farm: 2
  - wall: 1
  - hide: 3
  - wood: 5
    stone: 5
  - market: 1
  - main: 7
    barracks: 5
  - main: 10
    smith: 5
    stable: 1
  - stable: 3
  - wood: 9
    stone: 9
    wall: 5
  - barracks: 7
    market: 5
  - wood: 12
    iron: 8
  - main: 12
    wall: 10
  - stone: 12
    iron: 10
  - main: 15
    smith: 10
  - garage: 1
    market: 10
  - barracks: 15
    wood: 16
    stone: 16
    iron: 16
  - main: 20
    smith: 20
  - wood: 20
    stone: 20
  train:
    spear: 500
    sword: 500
    spy: 2000
    light: 0.5
    axe: 0.5
    ram: 200