env:
  global:
  - RUNNER=docker-compose run travis
language: generic
services:
  - docker  
before_install:
  - docker-compose -f docker/images/docker-compose.yml build
jobs:
  include:
    - stage: test
      before_script:
        - cd docker/travis/
      script: $RUNNER bundle exec rspec spec
      after_script:
        - if [[ "$TRAVIS_TEST_RESULT" == "0" ]] then $RUNNER bundle exec rake coveralls:push fi
stages:
  - test
cache: bundler