env:
  global:
    - CC_TEST_REPORTER_ID=e7f5d9a518ee5fa811fa38642f11119a495545796b1b3d929eadc0ae40229037
language: generic
services:
  - docker  
before_install:
  - docker-compose -f docker/images.yml build
jobs:
  include:
    - stage: test
      script: docker-compose run -e TRAVIS_TEST_RESULT=$TRAVIS_TEST_RESULT -e CI=true -e CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID -e TRAVIS=true test /bin/sh -c './cc-test-reporter before-build && bundle exec rspec spec  && bundle exec rake coveralls:push && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT'
stages:
  - test
cache: bundler