env:
  global:
      - STUB_USER=travis
      - STUB_PASS=travis123
      - STUB_WORLD=brp4
      - TZ=America/Sao_Paulo
      - CC_TEST_REPORTER_ID=eb32be7afe8adcd1513d01d47bcb0ade2fd870bd9ee735b6f5077fa88a09b88b
language: ruby
rvm:
  - 2.5.5
jobs:
  include:
    - stage: test
      before_script:
        - cd worker && curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - cd worker && chmod +x ./cc-test-reporter
        - cd worker && ./cc-test-reporter before-build
      script: cd worker && bundle exec rspec
      after_script:
        - cd worker && bundle exec rake coveralls:push
        - cd worker && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
stages:
  - test
cache: bundler
services:
  - mongodb