language: generic
env:
  - PATH=$PATH:/tmp/bin
services:
  - docker  
sudo: required
dist: xenial
# before_install:
#   - docker-compose -f docker/images/docker-compose.yml build
jobs:
  include:
    - stage: test
      before_script:
        - cd docker/travis/ 
        - docker-compose run travis /./cc-test-reporter before-build
      script: docker-compose run travis
      after_script:
        - docker-compose run travis bundle exec rake coveralls:push
        - docker-compose run travis /./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: deploy
      before_script:
        - cd docker/production/ssh
        - openssl aes-256-cbc -K $encrypted_680080ebd873_key -iv $encrypted_680080ebd873_iv -in secrets.tar.enc -out secrets.tar -d
        - tar xvf secrets.tar
        - cd ../../..
        - mkdir -p /tmp/bin/ && base=https://github.com/docker/machine/releases/download/v0.16.0 && curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/bin/docker-machine && chmod +x /tmp/bin/docker-machine
        - docker-machine create --driver generic --generic-ssh-key docker/production/ssh/id_rsa swarm
        - eval "$(docker-machine env swarm)"
        - docker-compose -f docker/images/docker-compose.yml build
        - cd docker/production
      script: docker-compose rm guardian && docker-compose up guardian -d
      after_script:
        - docker-machine rm -y swarm
stages:
  - name: test
    if: branch != docker-compose-deploy
  - name: deploy
    if: branch = docker-compose-deploy