language: ruby
rvm:
 - 2.5.1
bundler_args: --jobs=2
jobs:
  include:
    - stage: test
      script: bundle exec rspec spec
      after_script:
        - bundle exec rake coveralls:push
stages:
  - test