env:
  global:
    - CC_TEST_REPORTER_ID=e7f5d9a518ee5fa811fa38642f11119a495545796b1b3d929eadc0ae40229037
language: generic
services:
  - docker  
before_install:
  - docker-compose -f docker/images.yml build
jobs:
  include:
    - stage: test
      before_script:
        - docker-compose run test /bin/bash -c './cc-test-reporter before-build'
      script: docker-compose run test
      after_script:
        - docker-compose run test /bin/bash -c 'bundle exec rake coveralls:push'
        - docker-compose run test /bin/bash -c './cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT'
stages:
  - test
cache: bundler