language: generic
env:
  - PATH=$PATH:/tmp/bin
services:
  - docker  
# before_install:
#   - docker-compose -f docker/images/docker-compose.yml build
jobs:
  include:
    - stage: test
      before_script:
        - cd docker/travis/
        - docker-compose run travis /./cc-test-reporter before-build
      script: docker-compose run travis
      after_script:
        - docker-compose run travis bundle exec rake coveralls:push
        - docker-compose run travis /./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: deploy
      before_script:
        - mkdir -p /tmp/bin/ && base=https://github.com/docker/machine/releases/download/v0.16.0 && curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/bin/docker-machine
        - docker-machine create --driver generic swarm
      script: ls
      after_script:
        - docker-machine rm swarm
stages:
  - name: test
    if: branch != docker-compose-deploy
  - name: deploy
    if: branch = docker-compose-deploy