language: generic
services:
  - docker  
before_install:
  - docker-compose -f docker/images/docker-compose.yml build
jobs:
  include:
    - stage: test
      before_script:
        - cd docker/travis/
      script: docker-compose run travis bundle exec rspec spec
      after_script:
        - docker-compose run travis bundle exec rake coveralls:push
stages:
  - test
cache: bundler