language: generic
services:
  - docker  
before_install:
  - docker-compose -f docker/images.yml build
jobs:
  include:
    - stage: test
      script: docker-compose -f docker/travis.yml run $(env | cut -f1 -d= | sed 's/^/-e /') tests-ci
stages:
  - test
cache: bundler