language: generic
services:
  - docker  
before_install:
  - docker-compose -f docker/images/docker-compose.yml build
jobs:
  include:
    - stage: test
      before_script:
        - cd docker/travis
        - docker-compose run travis ./cc-test-reporter before-build
      script: docker-compose run travis bundle exec rspec spec
      after_script:
        - docker-compose run travis bundle exec rake coveralls:push
        - echo $TRAVIS_TEST_RESULT
        - docker-compose run -e TRAVIS_TEST_RESULT=$TRAVIS_TEST_RESULT travis ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
stages:
  - test
cache: bundler