version: '3.4'
services:
  test:
    image: lucianoshl/guardian-tests
    command: bundle exec rspec spec
    environment:
      ENV: test
      MONGO_URL: mongodb://mongo:27017/guardian-specs
      STUB_PASS: ${STUB_PASS}
      STUB_USER: lucianoshl
      STUB_WORLD: br95
      TZ: America/Sao_Paulo
    depends_on:
      - mongo
  mongo:
    image: mongo:latest

 