version: '3.4'
services:
  guardian:
    image: lucianoshl/guardian-base
    command: bundle exec foreman start -f Procfile.workers --timestamp=false
    volumes:
      - .:/usr/app
    environment:
      ENV: development
      MONGO_URL: mongodb://mongo:27017/guardian
      TZ: America/Sao_Paulo
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    stdin_open: true
    tty: true
  tests:
    image: lucianoshl/guardian-tests
    command: bundle exec rspec spec
    volumes:
      - .:/usr/app
      - /tmp:/tmp
    environment:
      ENV: test
      MONGO_URL: ${MONGO_URL:-mongodb://mongo:27017/guardian-specs}
      STUB_USER: ${STUB_USER}
      STUB_PASS: ${STUB_PASS}
      STUB_WORLD: ${STUB_WORLD}
      TZ: America/Sao_Paulo
    depends_on:
      - mongo
    stdin_open: true
    tty: true
  mongo:
    image: mongo:latest

 