version: '3.4'
services:
  base: 
    build:
      context: ../..
      dockerfile: ./docker/images/base.Dockerfile
    image: lucianoshl/guardian-base:latest
  test: 
    build:
      context: ../..
      dockerfile: ./docker/images/test.Dockerfile
    image: lucianoshl/guardian-tests:latest
    depends_on:
      - base
  fluentd: 
    build:
      context: .
      dockerfile: ./fluentd.Dockerfile
    image: lucianoshl/guardian-fluentd:latest
    depends_on:
      - base