version: '3.4'
services:
  base: 
    build:
      context: ../..
      dockerfile: base.Dockerfile
    image: lucianoshl/guardian-base
  test: 
    build:
      context: ../..
      dockerfile: test.Dockerfile
    image: lucianoshl/guardian-tests
    depends_on:
      - base