version: '3.4'
services:
  guardian:
    restart: always
    image: lucianoshl/guardian-base
    # command: bundle exec rake guardian:server
    command: /bin/sh -c 'while sleep 1; do echo "Hi"; done'
    environment:
      ENV: production
      MONGO_URL: mongodb://mongo:27017/guardian
      TZ: America/Sao_Paulo
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - fluentd
      - kibana
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: guardian
  mongo:
    restart: always
    image: mongo:latest
    volumes:
      - mongodata:/data/db
  fluentd:
    image: lucianoshl/guardian-fluentd
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.rollup.enabled=false
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: 'docker.elastic.co/kibana/kibana:7.1.0'
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    links:
      - elasticsearch
    ports:
      - '3001:5601'
volumes:
  esdata:
    driver: local
  mongodata:
    driver: local