version: '3.4'
services:
  guardian:
    restart: always
    image: lucianoshl/guardian-base
    command: bundle exec rake guardian:server
    environment:
      ENV: production
      MONGO_URL: mongodb://mongo:27017/guardian
      TZ: America/Sao_Paulo
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  mongo:
    restart: always
    image: mongo:latest

 