version: '3.4'
services:
  travis:
    image: lucianoshl/guardian-tests
    environment:
      CI: true
      TRAVIS: true
      RACK_ENV: test
      ENV: test
      MONGO_URL: mongodb://mongo:27017/guardian-specs
      STUB_PASS: ${STUB_PASS}
      STUB_USER: lucianoshl
      STUB_WORLD: br95
      TZ: America/Sao_Paulo
    depends_on:
      - mongo
  mongo:
    image: mongo:latest

 