version: '3.4'
services:
  travis:
    image: lucianoshl/guardian-tests:latest
    volumes:
      - ../..:/usr/app
    command: bundle exec rspec spec
    environment:
      CI: 'true'
      TRAVIS: 'true'
      RACK_ENV: test
      ENV: test
      MONGO_URL: mongodb://mongo:27017/guardian-specs
      STUB_USER: ${STUB_USER:-travis}
      STUB_PASS: ${STUB_PASS:-travis123}
      STUB_WORLD: ${STUB_WORLD:-br93}
      TZ: America/Sao_Paulo
      CC_TEST_REPORTER_ID: eb32be7afe8adcd1513d01d47bcb0ade2fd870bd9ee735b6f5077fa88a09b88b
      TRAVIS_TEST_RESULT: ${TRAVIS_TEST_RESULT:-1}
    depends_on:
      - mongo
  mongo:
    image: mongo:latest

 