development: 
  clients:
    default:
      uri: mongodb://localhost:27017/guardian-dev
      options: &defaults
        max_pool_size: 20
        min_pool_size: 20
  options:
    use_activesupport_time_zone: true

test:
  clients:
    default:
      uri: mongodb://localhost:27017/guardian-specs
      options: *defaults
  options:
    use_activesupport_time_zone: true

production:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
      options: *defaults
  options:
    use_activesupport_time_zone: true